// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sui/verify-cot-exemption": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SUI"
                ],
                "summary": "Verify COT exemption for a given niu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "niu",
                        "name": "niu",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CotExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CotExemptionReport": {
            "type": "object",
            "properties": {
                "id_empresa": {
                    "type": "string"
                },
                "niu": {
                    "type": "string"
                },
                "nombre_prestador": {
                    "type": "string"
                },
                "radicado": {
                    "type": "string"
                },
                "sigla": {
                    "type": "string"
                }
            }
        },
        "models.CotExemptionResponse": {
            "type": "object",
            "properties": {
                "report": {
                    "$ref": "#/definitions/models.TviSuperserviciosCotExemptionResponse"
                },
                "verification_timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Error": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                }
            }
        },
        "models.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.Error"
                }
            }
        },
        "models.TviSuperserviciosCotExemptionResponse": {
            "type": "object",
            "properties": {
                "listado_exentos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CotExemptionReport"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
