definitions:
  models.CotExemptionReport:
    properties:
      id_empresa:
        type: string
      niu:
        type: string
      nombre_prestador:
        type: string
      radicado:
        type: string
      sigla:
        type: string
    type: object
  models.CotExemptionResponse:
    properties:
      report:
        $ref: '#/definitions/models.TviSuperserviciosCotExemptionResponse'
      verification_timestamp:
        type: string
    type: object
  models.Error:
    properties:
      details:
        type: string
    type: object
  models.HTTPError:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
  models.TviSuperserviciosCotExemptionResponse:
    properties:
      listado_exentos:
        items:
          $ref: '#/definitions/models.CotExemptionReport'
        type: array
    type: object
info:
  contact: {}
paths:
  /sui/verify-cot-exemption:
    get:
      consumes:
      - application/json
      parameters:
      - description: niu
        in: query
        name: niu
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CotExemptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Verify COT exemption for a given niu
      tags:
      - SUI
swagger: "2.0"
