name: ci

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  Verify:
    runs-on: ubuntu-24.04

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: "Verify: Go Mod"
        run: go mod verify

  Lints:
    runs-on: ubuntu-24.04
    needs: Verify

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: "Setup: Install staticcheck"
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: "Setup: Install Golint"
        run: go install golang.org/x/lint/golint@latest
    
      - name: "Step: Go Vet"
        run: go vet -v ./...

      - name: "Step: Golint"
        run: golint -set_exit_status ./...

      - name: "Step: Staticcheck"
        run: staticcheck ./...

  Build:
    runs-on: ubuntu-24.04
    needs: Lints

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: "Step: Build"
        run: go build -v ./...
